version: "3"
services: 
  # mysql database
  mysql:
    container_name: mysql
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db_mysql:/var/lib/mysql
    ports:
      - "33066:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - mysql-network

  # web based mysql
  # adminer:
  #   container_name: adminer
  #   image: adminer
  #   restart: always
  #   ports:
  #     - "8091:8080"
  #   networks:
  #     - mysql-network

volumes:
  db_mysql:
    driver: local

# docker networks
networks:
  mysql-network:
    driver: bridge
